runtime: python37
env_variables:
  PYTHONHTTPSVERIFY: 1
layout:
  palette:
    primary: '#EC3944'
    secondary: '#4571C9'
    success: '#27C497'
    error: '#BC1A23'
  page:
    title: 'Lambda Go Links'
    favicon: '/favicon.ico'
  header:
    title: "Go Links"
    logo:
      url: "/_images/lambda.png"
      css:
        height: "40px"
    links:
      - directory

  footer:
    showSourceLink: false